name: Build and Publish Electron App

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Create draft release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          draft: true
          token: ${{ secrets.github_token }}
          prerelease: false
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            ---
            Describe the release notes here

      - name: Set up Node.js v19
        uses: actions/setup-node@v2
        with:
          node-version: 19.x

      - name: Build and publish Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: --publish always --prerelease
        env:
          GH_TOKEN: ${{ secrets.github_token }}
