name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Checkout
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          token: ${{ secrets.github_token }}

      - name: Set up Node.js v19
        uses: actions/setup-node@v2
        with:
          node-version: 19.x

      - name: Build and publish Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          args: --publish always --prerelease
        env:
          GH_TOKEN: ${{ secrets.github_token }}
